# Generated by Django 5.2.7 on 2025-10-24 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('crn', models.CharField(max_length=50, unique=True, verbose_name='CRN/Registro')),
                ('especialidade', models.CharField(blank=True, max_length=150, verbose_name='Especialidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutricionista',
                'verbose_name_plural': 'Nutricionistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do paciente')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('responsavel', models.CharField(blank=True, max_length=150, verbose_name='Responsável')),
                ('contato_responsavel', models.CharField(blank=True, max_length=50, verbose_name='Contato do responsável')),
                ('diagnostico_tea', models.CharField(blank=True, max_length=150, verbose_name='Diagnóstico (TEA)')),
                ('tipos_alimento', models.TextField(blank=True, verbose_name='Tipos de alimento que já come')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações clínicas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('nutricionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='sistema.nutricionista')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
